version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: container/Dockerfile
    env_file: .env
    ports:
      - 8000:8000

  postgres:
    image: postgres:16.2
    env_file: container/.env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    env_file: container/.env.minio
    volumes:
      - minio:/minio_files
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server /minio_files --console-address ":9001"


volumes:
  postgres-data:
  minio:
