version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - 8000:8000

  postgres:
    image: postgres:16.2
    env_file: docker/.env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
