# Generated by Django 5.0.3 on 2024-03-14 05:54

import django_countries.fields
import localflavor.generic.models
import taggit.managers
from django.db import migrations, models

import shark.id_generators.fields
import shark.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("address_name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "address_address_addition_1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (1st row)",
                    ),
                ),
                (
                    "address_address_addition_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (2nd row)",
                    ),
                ),
                (
                    "address_street",
                    models.CharField(max_length=100, verbose_name="street"),
                ),
                (
                    "address_street_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="street number"
                    ),
                ),
                ("address_city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "address_postal_code",
                    models.CharField(max_length=10, verbose_name="postal code"),
                ),
                ("address_state", models.CharField(blank=True, max_length=100)),
                (
                    "address_country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="country"
                    ),
                ),
                ("billing_address", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "invoice_dispatch_type",
                    models.CharField(
                        choices=[("email", "via email"), ("mail", "via mail")],
                        default="email",
                        max_length=20,
                        verbose_name="Invoice dispatch type",
                    ),
                ),
                (
                    "payment_timeframe_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "number",
                    shark.id_generators.fields.IdField(
                        blank=True, editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "language",
                    shark.utils.fields.LanguageField(
                        blank=True, max_length=7, verbose_name="language"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("direct_debit", "Direct debit"),
                        ],
                        default="invoice",
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "account_iban",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        help_text="International Bank Account Number",
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "account_bic",
                    localflavor.generic.models.BICField(
                        blank=True,
                        help_text="Bank Identifier Code",
                        max_length=11,
                        verbose_name="BIC",
                    ),
                ),
                ("account_bank_name", models.CharField(blank=True, max_length=50)),
                (
                    "vatin",
                    models.CharField(
                        blank=True,
                        help_text="Value added tax identification number",
                        max_length=14,
                        verbose_name="VATIN",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
            },
        ),
    ]
