# Generated by Django 5.0.6 on 2024-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="daily rate",
            ),
        ),
    ]
