# Generated by Django 5.0.7 on 2025-04-02 11:41

import django_countries.fields
import localflavor.generic.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirectDebitBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "creditor_id",
                    models.CharField(max_length=20, verbose_name="creditor id"),
                ),
                (
                    "creditor_name",
                    models.CharField(max_length=70, verbose_name="creditor name"),
                ),
                (
                    "creditor_country",
                    models.CharField(max_length=2, verbose_name="creditor country"),
                ),
                (
                    "creditor_iban",
                    localflavor.generic.models.IBANField(
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                        verbose_name="creditor IBAN",
                    ),
                ),
                (
                    "creditor_bic",
                    localflavor.generic.models.BICField(
                        max_length=11, verbose_name="creditor BIC"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Must be min. 5 TARGET dates in the future for the first transaction and 2target days in the future for recurring transactions.",
                        verbose_name="due date",
                    ),
                ),
                (
                    "mandate_type",
                    models.CharField(
                        choices=[("CORE", "CORE"), ("COR1", "COR1"), ("B2B", "B2B")],
                        max_length=4,
                        verbose_name="mandate type",
                    ),
                ),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[("FRST", "FRST"), ("RCUR", "RCUR")],
                        max_length=4,
                        verbose_name="sequence type",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="executed_at"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirectDebitMandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        unique=True,
                        verbose_name="mandate reference",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(default="DE", max_length=2),
                ),
                (
                    "iban",
                    localflavor.generic.models.IBANField(
                        help_text="International Bank Account Number",
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    localflavor.generic.models.BICField(
                        help_text="Bank Identifier Code",
                        max_length=11,
                        verbose_name="BIC",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50)),
                (
                    "signed_at",
                    models.DateField(blank=True, null=True, verbose_name="signed_at"),
                ),
                (
                    "revoked_at",
                    models.DateField(blank=True, null=True, verbose_name="revoked_at"),
                ),
                (
                    "last_used",
                    models.DateField(blank=True, null=True, verbose_name="last_used"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CORE", "CORE"), ("COR1", "COR1"), ("B2B", "B2B")],
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "SEPA direct debit mandate",
                "verbose_name_plural": "SEPA direct debit mandates",
            },
        ),
        migrations.CreateModel(
            name="DirectDebitTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("reference", models.CharField(max_length=140)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="amount"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
