# Generated by Django 5.0.7 on 2025-04-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0003_initial"),
        ("customer", "0002_initial"),
        ("sepa", "0001_initial"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directdebitbatch",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="directdebitmandate",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AddField(
            model_name="directdebittransaction",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sepa.directdebitbatch",
                verbose_name="SEPA DD batch",
            ),
        ),
        migrations.AddField(
            model_name="directdebittransaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AddField(
            model_name="directdebittransaction",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="directdebittransaction",
            name="mandate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sepa.directdebitmandate",
                verbose_name="SEPA DD mandate",
            ),
        ),
    ]
