# Generated by Django 3.2.7 on 2021-09-04 17:25

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import shark.utils.date
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=100, verbose_name="name"),
                ),
                (
                    "sender_address_addition_1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (1st row)",
                    ),
                ),
                (
                    "sender_address_addition_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (2nd row)",
                    ),
                ),
                (
                    "sender_street",
                    models.CharField(blank=True, max_length=100, verbose_name="street"),
                ),
                (
                    "sender_street_number",
                    models.CharField(max_length=20, verbose_name="street number"),
                ),
                (
                    "sender_city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "sender_postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="postal code"
                    ),
                ),
                ("sender_state", models.CharField(blank=True, max_length=100)),
                (
                    "sender_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=100, verbose_name="name"),
                ),
                (
                    "recipient_address_addition_1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (1st row)",
                    ),
                ),
                (
                    "recipient_address_addition_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="address addition (2nd row)",
                    ),
                ),
                (
                    "recipient_street",
                    models.CharField(blank=True, max_length=100, verbose_name="street"),
                ),
                (
                    "recipient_street_number",
                    models.CharField(max_length=20, verbose_name="street number"),
                ),
                (
                    "recipient_city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "recipient_postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="postal code"
                    ),
                ),
                ("recipient_state", models.CharField(blank=True, max_length=100)),
                (
                    "recipient_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("invoice", "invoice"),
                            ("payment_reminder", "payment reminder"),
                            ("bank_statement", "bank statement"),
                            ("quote", "quote"),
                            ("misc", "miscellaneous"),
                            ("sepa_dd_mandate", "SEPA direct debit mandate"),
                        ],
                        max_length=20,
                        verbose_name="direction",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("internal", "internal"),
                            ("inbound", "inbound"),
                            ("outbound", "outbound"),
                        ],
                        max_length=10,
                        verbose_name="direction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=shark.utils.date.today,
                        help_text="Date as written on the document.",
                        verbose_name="date",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents",
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="file size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Auto detected from uploaded file",
                        max_length=100,
                        verbose_name="MIME type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "email"),
                            ("download", "download"),
                            ("mail", "mail"),
                            ("fax", "fax"),
                            ("receipt", "receipt"),
                            ("self", "self"),
                        ],
                        help_text="Where does this document come from?",
                        max_length=10,
                        verbose_name="original",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "received",
                    models.DateField(
                        default=shark.utils.date.today,
                        help_text="Date when the document was received.",
                        verbose_name="received",
                    ),
                ),
                (
                    "thumbnail_small",
                    models.ImageField(editable=False, upload_to="documents"),
                ),
                (
                    "thumbnail_medium",
                    models.ImageField(editable=False, upload_to="documents"),
                ),
                (
                    "thumbnail_large",
                    models.ImageField(editable=False, upload_to="documents"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="tags",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendor.vendor",
                        verbose_name="vendor",
                    ),
                ),
            ],
        ),
    ]
