name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

env:
  POETRY_VERSION: 1.7.1
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Ensure /opt/hostedtoolcache exists (for self-hosted runners)
        run: sudo mkdir -p /opt/hostedtoolcache/Python && sudo chown runner:runner /opt/hostedtoolcache/Python

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --without dev

      - name: Run tests
        run: python manage.py test
