name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

env:
  UV_VERSION: 0.6.11

jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Ensure /opt/hostedtoolcache exists (for self-hosted runners)
        run: sudo mkdir -p /opt/hostedtoolcache/Python && sudo chown runner:runner /opt/hostedtoolcache/Python

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/$UV_VERSION/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Check for linter errors
        run: uv run ruff check

      - name: Run tests
        run: uv run python manage.py test
