# Generated by Django 5.0.3 on 2024-03-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_set",
                to="billing.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceArticleItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.invoiceitem",),
        ),
        migrations.CreateModel(
            name="InvoiceTimeItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.invoiceitem",),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("customer", "number")},
        ),
    ]
