# Generated by Django 4.2.10 on 2024-02-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_set",
                to="billing.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoiceitem",
            unique_together={("invoice", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("customer", "number")},
        ),
    ]
