# Generated by Django 5.0.6 on 2024-06-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.invoicetemplate",
            ),
        ),
    ]
