# Generated by Django 5.0.6 on 2024-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_invoice_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicetemplate",
            name="is_selected",
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit",
            field=models.CharField(
                blank=True, choices=[("h", "Hours"), ("d", "Days"), ("m", "Months")]
            ),
        ),
    ]
