# Generated by Django 5.0.6 on 2024-07-01 12:26

import django.utils.timezone
from django.db import migrations, models

import shark.id_generators.fields


def set_issue_date_to_created_at(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    for invoice in Invoice.objects.all():
        invoice.issue_date = invoice.created_at.date()
        invoice.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_remove_invoicetemplate_is_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Invoice issue date"
            ),
        ),
        migrations.RunPython(set_issue_date_to_created_at, noop),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=shark.id_generators.fields.IdField(
                blank=True, max_length=32, unique=True, verbose_name="number"
            ),
        ),
    ]
